apiVersion: v1
kind: Service
metadata:
  name: rss2rm
spec:
  type: NodePort
  selector:
    app: rss2rm
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: rss2rm-cert
spec:
  domains:
    - ${DOMAIN}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rss2rm
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: ${STATIC_IP_NAME}
    networking.gke.io/managed-certificates: rss2rm-cert
spec:
  defaultBackend:
    service:
      name: rss2rm
      port:
        number: 8080
